### ISSUE TITLE
sudo apt-get update && sudo apt-get upgrade MARK2 sending ERRORS!

### ISSUE THREAD

**Issue by TomLewis** [gsand/mark2#64] opened 2016-08-25 12:07 UTC
as soon as I saw twisted pop up on the update to debian, I just knew mark2 would break.
**mark2 start:**
`2016-08-25 13:04:00 # starting piratecraft
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/tom/mark2/mk2/services/process.py", line 107, in server_starting
            self.stat_process.start(self.parent.config['java.ps.interval'])
          File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 194, in start
            self()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in __call__
            d = defer.maybeDeferred(self.f, *self.a, **self.kw)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/tom/mark2/mk2/services/process.py", line 165, in update_stat
            except psutil.error.NoSuchProcess:
        exceptions.AttributeError: 'module' object has no attribute 'error'
`

and again:
`tom@ns501023:~/piratecraft/survival$ mark2 start
2016-08-25 13:04:31 # mark2 starting...
2016-08-25 13:04:31 # starting survival
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/tom/mark2/mk2/services/process.py", line 107, in server_starting
            self.stat_process.start(self.parent.config['java.ps.interval'])
          File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 194, in start
            self()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in __call__
            d = defer.maybeDeferred(self.f, *self.a, **self.kw)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/tom/mark2/mk2/services/process.py", line 165, in update_stat
            except psutil.error.NoSuchProcess:
        exceptions.AttributeError: 'module' object has no attribute 'error'
`
when I attach to a server, CPU is broken, mem is broken, I just hope this wont crash the server.

**Comment by Trikolon** [comment] 2016-08-27 16:21
Same issue here. Ubuntu Server 16.04

**Comment by gsand** [comment] 2016-09-04 18:13
I'm on mobile, will fix tonight.

**Comment by FrozenBeard** [comment] 2016-09-11 12:30
@gsand any luck? I did a git pull today, but it still exists.

**Comment by gsand** [comment] 2016-09-11 20:36
Haven't had time, I'm very busy IRL. Sorry about that.

**Comment by FrozenBeard** [comment] 2016-09-11 21:02
No sweat man

**Comment by gsand** [comment] 2016-09-11 21:32
I'm running an ubuntu virtual machine and I'm unable to reproduce it, Will start all over in a bit. :(

**Comment by gsand** [comment] 2016-09-11 23:10
Hey fellas.

'sudo apt-get remove python-feedparser python-psutil python-twisted-core python-twisted-mail python-twisted-web python-twisted-words python-urwid'

Then

'cd /usr/mark2'

Then

'pip install -r requirements.txt'

Should work. :laughing:

**Comment by Trikolon** [comment] 2016-09-15 12:59
Make sure to only run 

> sudo apt-get remove python-feedparser python-psutil python-twisted-core python-twisted-mail python-twisted-web python-twisted-words python-urwid

 if you don't have any packages like 'letsencrypt' depending on it.
Installing the dependencies from the requirements.txt file did not work for me. I've installed the latest version of each python package manually. Everything seems to work now (no error messages). Thank you!

**Comment by FrozenBeard** [comment] 2016-09-17 15:45
Im glad I tried this on my test server where I use Tmux... 
It completely failed.

Every package threw a "failed" at me, heres a snippety from one of the failed messages:

`  ----------------------------------------
  Failed building wheel for Twisted
  Running setup.py clean for Twisted
  Running setup.py bdist_wheel for urwid ... done
  Stored in directory: /root/.cache/pip/wheels/e7/bb/9d/d7f7fcc9b3aeae20cf4685667635002415629e6395ff2dda7d
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hascox/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpSPWevApip-wheel- --python-tag cp27:
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory

      No working compiler found, or bogus compiler options
      passed to the compiler from Python's distutils module.
      See the error messages above.
      (If they are about -mno-fused-madd and you are on OS/X 10.8,
      see http://stackoverflow.com/questions/22313407/ .)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-hascox/cryptography/setup.py", line 334, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 631, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 874, in best_match
      return self.obtain(req, installer)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 886, in obtain
      return installer(requirement)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 338, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 666, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 856, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1066, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with 1`

**Comment by FrozenBeard** [comment] 2016-12-24 00:33
I took another look at this, and in the end figured it out to be needing to install these thigns;
`sudo apt-get install build-essential libssl-dev libffi-dev python-dev`

Not sure if I need them all, but that seemed to work.

**Comment by Column01** [comment] 2021-07-27 03:28
Should be fixed with python 3 port with a reinstall

**Closed by Column01** 2021-07-27 03:28 UTC
Labels: discussion
